### ISSUE TITLE
Typo in code - config.svelte.predender_default 

### ISSUE THREAD

**Issue by hangtwenty** [nning/svelte-rails#5]
I haven't tried running this, was just perusing the source and noticed this:

```ruby
    # Prerender (SSR) by default (i.e. without passing `prerender:true` to the view helper)
    config.svelte.predender_default = false
```

Link to source: https://github.com/nning/svelte-rails/blob/master/lib/svelte/rails/railtie.rb

**Comment by nning** [comment]
Thanks very much, good catch!
