### ISSUE TITLE
CSS classes are missing when Rails runs in produciton

### ISSUE THREAD

**Issue by oneearedrabbit** [nning/svelte-rails#6]
I'm looking for a guidance how to run svelte-rails in production.

My issue is when I precompile assets: `RAILS_ENV=production bundle exec rake assets:precompile` and run Rails in production mode: `RAILS_SERVE_STATIC_FILES=yes RAILS_ENV=production rails s`, Svelte components are loosing their classes that are defined in `<style>...</style>` section.

This issue is not happening if Rails runs in development. I'm using a preinstalled Hello.svelte component as a test. 

Not sure if it gives a clue, but if I run `RAILS_ENV=development ./bin/webpack` & restart Rails production, the issue goes away.

**Comment by wyozi** [comment]
Did you embed stylesheet packs in application view?

```
 <%= stylesheet_pack_tag 'application' %>
```

**Comment by oneearedrabbit** [comment]
Thanks! I think you're right, not sure how I missed it. Now, I'm getting a Rails error that css file is missing in `manifest.json`, but it must be a Rails specific issue. I'm trying to figure out how to resolve it. It seems to be some recent changes in Rails, i.e. https://github.com/rails/webpacker/issues/2605

**Comment by oneearedrabbit** [comment]
I'll try again with a new Rails6 application and write down steps I followed, it's going to be easier to figure out what's missing.

**Comment by oneearedrabbit** [comment]
Interesting enough a new Rails setup works as expected. I'll close this ticket out, must be a local configuration issue then. The only thing that could be worth mentioning in `README` is `pack_tag`, but I'll leave it up to you. Thanks for your help.
